---
title: "R note"
author: "H24041066"
date: "2019/5"
output: html_document
---
-----------

## *Content*

a. Basic
b. more

------
------

### a. Basic

+ **Operator**
  1. Arithmetic
  2. Natural logarithm
  3. Root
  
  ...and more

::

1. Arithmetic: `+` `-` `*` `/` `^()`

$3+5$ ,  $10+4$ ,  $2\times23$ ,   $3^{2}$
```{r, comment=NA, echo=TRUE, collapse = TRUE}
3+5

10-4

2*23

16/4

3^(2)
```



::

2. Natural logarithm: `exp()`

 $e^3$
```{r}
exp(3)
```



::

3. Root: `sqrt()`

$\surd3$
```{r}
sqrt(3)
```
------
-------

+ **define object**
  1. numeric
  2. character
  3. logic
  4. vector
  5. factor
  6. list
  
  ...and more

  
::


1. numeric: `x <- number`

Let a = 3, b = 4, c = -10
```{r, comment=NA, collapse = TRUE}
a <- 3
a

b <- 4
b

c <- -10
c
```

numeric "data type" :
1. integer
2. number

more tools

* `str()`
* `as.integer()`, `is.integer()`
* `as.numeric()`, `is.numeric()`


::

2. character: `'x'` , `"word"`

Let a be a, M be math
```{r, comment=NA}
a <- 'a'
a

M <- "math"
M
```


more tools

* `as.character()`, `is.character()`
  
::

3. logic: `x <- TRUE`


```{r, comment=NA, collapse = TRUE}
a <- TRUE
a

b <- FALSE
b
```


more tools

* `as.logic()`, `is.logic()`

::

4. vector: `c()`, `object[index]`


```{r, comment=NA, collapse = TRUE}
a <- c(1,2,3,4,5)
a

a[1]

a[1:3]
```


more tools

* `as.vector()`, `is.vector()`

::

5. factor: `factor()`


```{r, comment=NA, collapse = TRUE}
gender <- c("boy", "girl", "boy", "boy", "girl") 
gender <- factor(gender)   
gender
```


more tools

* `as.factor()`, `is.factor()`
* `level()`

::

6. list: `list()`, `list$`, `list[[index]]`


```{r, comment=NA, collapse = TRUE}
Amy <- list(gender="man", age=23, food=c("watermelon", "apple"))
Amy

Amy$age

Amy[2]

Amy[[2]]
```


more tools

* `as.list()`, `is.list()`

--------
--------
+ **start**
  1. install.package, library
  2. data.frame
  3. read.csv, read.txt
  
  ...and more
  
::

-------
-------
+ **level 1 anaylsis**
  1. summary
  2. anova
  3. plot
  4. sample
  5. function
  
  ...and more
  
::

  
  
  